spring:
  datasource:

    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_oms?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:/mapper/oms/*.xml
server:
  port: 12000